services:
  database:
    image: mysql:8.0
    container_name: todo-app-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - ./mysql/mysql_data:/var/lib/mysql
      - ./mysql/mysql.cnf:/etc/my.cnf:ro
      # - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - todo-app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  mysql_data:
    driver: local

networks:
  todo-app-network:
    driver: bridge    